# License: LGPL-3.0-or-later
name: Main Branch task
on: 
  push:
    branches: 
      - main
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
# this version used for running various tools
  tool_node_version: "14.x"
  tool_ruby_version: "2.7.6"
jobs:
  npm-package-download: # this downloads and caches all of the packages. That way if a future job fails, the caching will still occur
      name: Download and cache any npm packages
      needs: changes
      if: ${{ contains(needs.changes.outputs.filters, 'build-js') }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-20.04]
          node: ["14.x"]
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node }}
            cache: 'yarn'
        - run: yarn install --frozen-lockfile
  
  gem-package-download: # this downloads and caches all of the packages. That way if a future job fails, the caching will still occur
    name: Download and cache any gem packages
    needs: changes
    if: ${{ contains(needs.changes.outputs.filters, 'build-ruby') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        ruby: [2.7.6]
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true